trigger:
- main
pool: server
steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName
    serviceConnection: 'myconnection'

    method: 'GET'
    headers: |
      {
      "Content-Type":"application/json"
      }
    urlSuffix: 'http://worldclockapi.com/api/json/est/now'
    waitForCompletion: 'false'