trigger:
- main
pool:
  name: 'CTSLAPTOP'
steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    method: 'GET'
    headers: |
      {
      "Content-Type":"application/json"
      }
    urlSuffix: 'http://worldclockapi.com/api/json/est/now'
    waitForCompletion: 'false'